### ISSUE TITLE
The non-sucking monitoring manifesto

### ISSUE THREAD

**Issue by gleicon** [solarce/hangops.github.com#4]
Given that obfuscurity nailed an excellent review here: https://speakerdeck.com/u/obfuscurity/p/the-state-of-open-source-monitoring I think that the foot notes have good material to come with the second part of this: http://lusislog.blogspot.com.br/2011/06/why-monitoring-sucks.html.

What I would expect is that the general components (data collection, storage, event correlation and charts) get mapped and overall recs are given to the beginner and even to the experienced in terms of real use cases. 

Plus it would be nice to have a list of people that (given their employee's permission) could give a tour or talks about their in-house monitoring solutions (I think the MozillaIT guys might have interesting stuff to tell).

**Comment by cshields** [comment]
+1  We can show off our monitoring stuff at Mozilla..  I just did so in a closed presentation this week.  However, it was heavy on the caveat that "what we have now could be so much better".  I think our trending might be perceived as a bit run-of-the-mill, but where we might show off something unique is in the way we interface with nagios through irc bots.

Maybe schedule this hangops topic on a day where obfuscurity can attend (if he would agree to)?

**Comment by sixty4k** [comment]
+1

**Comment by obfuscurity** [comment]
I'd love to. I'd only ask that we try and a) do it earlier on Fridays or b) pick a different day. Fridays at late afternoon are really tough for me between work and family commitments.

**Comment by solarce** [comment]
This was done in a couple of sessions, gonna close it

**Comment by gleicon** [comment]
thanks !
